Update documentary.md and add Lo and Behold
greybax/awesome-IT-films pull request #107
Opened 2020-10-23 17:53 UTC by notgitika

2020-10-28 16:52 UTC, greybax requested changes

2020-10-28 16:52 UTC, greybax commented on build/documentary.md
> +#### Lo and Behold: Reveries of the Connected World
do not update any files from `build` folder... you should add new films into *_prebuild.md accordingly

2020-10-31 01:53 UTC, shameka2 reviewed
I would like to know more about the artificial intelligence and technology in our lives.

2020-11-02 01:03 UTC, greybax commented
Closed due to inactivity...

2020-11-02 01:03 UTC, closed without merging