Update movies_prebuilt.md
greybax/awesome-IT-films pull request #138
Opened 2022-10-01 02:38 UTC by AnuragRoy485

2022-10-01 05:45 UTC, greybax requested changes
Hi @AnuragRoy485, how this movie is related to IT/hackers/programmers/coding/etc.. ?

2022-10-01 17:34 UTC, AnuragRoy485 commented
> Hi @AnuragRoy485, how this movie is related to IT/hackers/programmers/coding/etc.. ?

Okay So I'll change and again upload.

2022-10-04 18:56 UTC, greybax requested changes

2022-10-04 18:56 UTC, greybax commented on movies_prebuilt.md
> +#### Who Am I
its already in the list https://github.com/greybax/awesome-IT-films/blob/master/movies_prebuilt.md#who-am-i

2022-10-10 20:30 UTC, closed without merging